import { PluriArea } from "./PluriArea.model";

export class Pluri {
  id: number;
  nome: string;
  codigo: string;
  trimestre: number;
  anoAplicacao: number;
  dataInicioPluri: Date | null;
  dataFimPluri: Date | null;
  dataInicioIndicacaoDocentes: Date | null;
  dataFimIndicacaoDocentes: Date | null;
  dataInicioEnvioQuestoes: Date | null;
  dataFimEnvioQuestoes: Date | null;
  dataInicioDiagramacao: Date | null;
  dataFimDiagramacao: Date | null;
  dataInicioRevisao: Date | null;
  dataFimRevisao: Date | null;
  dataInicioImpressao: Date | null;
  dataFimImpressao: Date | null;
  dataInicioEnsalamento: Date | null;
  dataFimEnsalamento: Date | null;
  dataInicioLancamentoNotas: Date | null;
  dataFimLancamentoNotas: Date | null;
  dataInicioCorrecaoRedacao: Date | null;
  dataFimCorrecaoRedacao: Date | null;
  dataInicioEnviarRecurso: Date | null;
  dataFimEnviarRecurso: Date | null;
  dataInicioAnaliseRecurso: Date | null;
  dataFimAnaliseRecurso: Date | null;
  dataInicioAtualizacaoNotas: Date | null;
  dataFimAtualizacaoNotas: Date | null;
  dataAplicacao: Date | null;
  dataReaplicacao: Date | null;
  dataDivulgacaoNotas: Date | null;
  realizado: boolean;
  areasPluri?: PluriArea[] | null;

  constructor() {
    this.id = 0;
    this.nome = '';
    this.codigo = '';
    this.trimestre = 0;
    this.anoAplicacao = 0;
    this.dataInicioPluri = null;
    this.dataFimPluri = null;
    this.dataInicioIndicacaoDocentes = null;
    this.dataFimIndicacaoDocentes = null;
    this.dataInicioEnvioQuestoes = null;
    this.dataFimEnvioQuestoes = null;
    this.dataInicioDiagramacao = null;
    this.dataFimDiagramacao = null;
    this.dataInicioRevisao = null;
    this.dataFimRevisao = null;
    this.dataInicioImpressao = null;
    this.dataFimImpressao = null;
    this.dataInicioEnsalamento = null;
    this.dataFimEnsalamento = null;
    this.dataInicioLancamentoNotas = null;
    this.dataFimLancamentoNotas = null;
    this.dataInicioCorrecaoRedacao = null;
    this.dataFimCorrecaoRedacao = null;
    this.dataInicioEnviarRecurso = null;
    this.dataFimEnviarRecurso = null;
    this.dataInicioAnaliseRecurso = null;
    this.dataFimAnaliseRecurso = null;
    this.dataInicioAtualizacaoNotas = null;
    this.dataFimAtualizacaoNotas = null;
    this.dataAplicacao = null;
    this.dataReaplicacao = null;
    this.dataDivulgacaoNotas = null;
    this.realizado = false;
    this.areasPluri = null;
  }
}
